FROM quay.io/buildah/stable:v1.37.5

# Set up the working directory
USER build
WORKDIR /home/build
RUN export STORAGE_DRIVER=vfs

# Add the plugin binary
ADD release/linux/amd64/buildah-docker /bin/

# Set the entrypoint to the plugin binary
ENTRYPOINT ["/bin/buildah-docker"]
